global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: tunneledge
    static_configs:
      - targets:
          - registry:9090
          - gateway:9090
          - gateway-2:9090
          - dashboard:9090
          - agent:9090
