// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: proto/registry/v1/registry.proto

package registryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	LocalAddr     string                 `protobuf:"bytes,4,opt,name=local_addr,json=localAddr,proto3" json:"local_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTunnelRequest) Reset() {
	*x = RegisterTunnelRequest{}
	mi := &file_proto_registry_v1_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTunnelRequest) ProtoMessage() {}

func (x *RegisterTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_v1_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTunnelRequest.ProtoReflect.Descriptor instead.
func (*RegisterTunnelRequest) Descriptor() ([]byte, []int) {
	return file_proto_registry_v1_registry_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterTunnelRequest) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *RegisterTunnelRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterTunnelRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterTunnelRequest) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

type RegisterTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	PublicAddr    string                 `protobuf:"bytes,2,opt,name=public_addr,json=publicAddr,proto3" json:"public_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTunnelResponse) Reset() {
	*x = RegisterTunnelResponse{}
	mi := &file_proto_registry_v1_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTunnelResponse) ProtoMessage() {}

func (x *RegisterTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_v1_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTunnelResponse.ProtoReflect.Descriptor instead.
func (*RegisterTunnelResponse) Descriptor() ([]byte, []int) {
	return file_proto_registry_v1_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterTunnelResponse) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *RegisterTunnelResponse) GetPublicAddr() string {
	if x != nil {
		return x.PublicAddr
	}
	return ""
}

type DeregisterTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterTunnelRequest) Reset() {
	*x = DeregisterTunnelRequest{}
	mi := &file_proto_registry_v1_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterTunnelRequest) ProtoMessage() {}

func (x *DeregisterTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_v1_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterTunnelRequest.ProtoReflect.Descriptor instead.
func (*DeregisterTunnelRequest) Descriptor() ([]byte, []int) {
	return file_proto_registry_v1_registry_proto_rawDescGZIP(), []int{2}
}

func (x *DeregisterTunnelRequest) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

type DeregisterTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterTunnelResponse) Reset() {
	*x = DeregisterTunnelResponse{}
	mi := &file_proto_registry_v1_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterTunnelResponse) ProtoMessage() {}

func (x *DeregisterTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_v1_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterTunnelResponse.ProtoReflect.Descriptor instead.
func (*DeregisterTunnelResponse) Descriptor() ([]byte, []int) {
	return file_proto_registry_v1_registry_proto_rawDescGZIP(), []int{3}
}

type GetTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTunnelRequest) Reset() {
	*x = GetTunnelRequest{}
	mi := &file_proto_registry_v1_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTunnelRequest) ProtoMessage() {}

func (x *GetTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_v1_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTunnelRequest.ProtoReflect.Descriptor instead.
func (*GetTunnelRequest) Descriptor() ([]byte, []int) {
	return file_proto_registry_v1_registry_proto_rawDescGZIP(), []int{4}
}

func (x *GetTunnelRequest) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

type GetTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	PublicAddr    string                 `protobuf:"bytes,3,opt,name=public_addr,json=publicAddr,proto3" json:"public_addr,omitempty"`
	LocalAddr     string                 `protobuf:"bytes,4,opt,name=local_addr,json=localAddr,proto3" json:"local_addr,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastHeartbeat int64                  `protobuf:"varint,6,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTunnelResponse) Reset() {
	*x = GetTunnelResponse{}
	mi := &file_proto_registry_v1_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTunnelResponse) ProtoMessage() {}

func (x *GetTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_v1_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTunnelResponse.ProtoReflect.Descriptor instead.
func (*GetTunnelResponse) Descriptor() ([]byte, []int) {
	return file_proto_registry_v1_registry_proto_rawDescGZIP(), []int{5}
}

func (x *GetTunnelResponse) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *GetTunnelResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetTunnelResponse) GetPublicAddr() string {
	if x != nil {
		return x.PublicAddr
	}
	return ""
}

func (x *GetTunnelResponse) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

func (x *GetTunnelResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetTunnelResponse) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

type ListTunnelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTunnelsRequest) Reset() {
	*x = ListTunnelsRequest{}
	mi := &file_proto_registry_v1_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTunnelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTunnelsRequest) ProtoMessage() {}

func (x *ListTunnelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_v1_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTunnelsRequest.ProtoReflect.Descriptor instead.
func (*ListTunnelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_registry_v1_registry_proto_rawDescGZIP(), []int{6}
}

type ListTunnelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnels       []*GetTunnelResponse   `protobuf:"bytes,1,rep,name=tunnels,proto3" json:"tunnels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTunnelsResponse) Reset() {
	*x = ListTunnelsResponse{}
	mi := &file_proto_registry_v1_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTunnelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTunnelsResponse) ProtoMessage() {}

func (x *ListTunnelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_v1_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTunnelsResponse.ProtoReflect.Descriptor instead.
func (*ListTunnelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_registry_v1_registry_proto_rawDescGZIP(), []int{7}
}

func (x *ListTunnelsResponse) GetTunnels() []*GetTunnelResponse {
	if x != nil {
		return x.Tunnels
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_registry_v1_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_v1_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_registry_v1_registry_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatRequest) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_registry_v1_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_v1_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_registry_v1_registry_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

var File_proto_registry_v1_registry_proto protoreflect.FileDescriptor

const file_proto_registry_v1_registry_proto_rawDesc = "" +
	"\n" +
	" proto/registry/v1/registry.proto\x12\x16tunneledge.registry.v1\"\x84\x01\n" +
	"\x15RegisterTunnelRequest\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"local_addr\x18\x04 \x01(\tR\tlocalAddr\"V\n" +
	"\x16RegisterTunnelResponse\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x1f\n" +
	"\vpublic_addr\x18\x02 \x01(\tR\n" +
	"publicAddr\"6\n" +
	"\x17DeregisterTunnelRequest\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\"\x1a\n" +
	"\x18DeregisterTunnelResponse\"/\n" +
	"\x10GetTunnelRequest\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\"\xd1\x01\n" +
	"\x11GetTunnelResponse\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1f\n" +
	"\vpublic_addr\x18\x03 \x01(\tR\n" +
	"publicAddr\x12\x1d\n" +
	"\n" +
	"local_addr\x18\x04 \x01(\tR\tlocalAddr\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12%\n" +
	"\x0elast_heartbeat\x18\x06 \x01(\x03R\rlastHeartbeat\"\x14\n" +
	"\x12ListTunnelsRequest\"Z\n" +
	"\x13ListTunnelsResponse\x12C\n" +
	"\atunnels\x18\x01 \x03(\v2).tunneledge.registry.v1.GetTunnelResponseR\atunnels\"/\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\")\n" +
	"\x11HeartbeatResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive2\xa5\x04\n" +
	"\x0fRegistryService\x12o\n" +
	"\x0eRegisterTunnel\x12-.tunneledge.registry.v1.RegisterTunnelRequest\x1a..tunneledge.registry.v1.RegisterTunnelResponse\x12u\n" +
	"\x10DeregisterTunnel\x12/.tunneledge.registry.v1.DeregisterTunnelRequest\x1a0.tunneledge.registry.v1.DeregisterTunnelResponse\x12`\n" +
	"\tGetTunnel\x12(.tunneledge.registry.v1.GetTunnelRequest\x1a).tunneledge.registry.v1.GetTunnelResponse\x12f\n" +
	"\vListTunnels\x12*.tunneledge.registry.v1.ListTunnelsRequest\x1a+.tunneledge.registry.v1.ListTunnelsResponse\x12`\n" +
	"\tHeartbeat\x12(.tunneledge.registry.v1.HeartbeatRequest\x1a).tunneledge.registry.v1.HeartbeatResponseB)Z'tunneledge/proto/registry/v1;registryv1b\x06proto3"

var (
	file_proto_registry_v1_registry_proto_rawDescOnce sync.Once
	file_proto_registry_v1_registry_proto_rawDescData []byte
)

func file_proto_registry_v1_registry_proto_rawDescGZIP() []byte {
	file_proto_registry_v1_registry_proto_rawDescOnce.Do(func() {
		file_proto_registry_v1_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_registry_v1_registry_proto_rawDesc), len(file_proto_registry_v1_registry_proto_rawDesc)))
	})
	return file_proto_registry_v1_registry_proto_rawDescData
}

var file_proto_registry_v1_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_registry_v1_registry_proto_goTypes = []any{
	(*RegisterTunnelRequest)(nil),    // 0: tunneledge.registry.v1.RegisterTunnelRequest
	(*RegisterTunnelResponse)(nil),   // 1: tunneledge.registry.v1.RegisterTunnelResponse
	(*DeregisterTunnelRequest)(nil),  // 2: tunneledge.registry.v1.DeregisterTunnelRequest
	(*DeregisterTunnelResponse)(nil), // 3: tunneledge.registry.v1.DeregisterTunnelResponse
	(*GetTunnelRequest)(nil),         // 4: tunneledge.registry.v1.GetTunnelRequest
	(*GetTunnelResponse)(nil),        // 5: tunneledge.registry.v1.GetTunnelResponse
	(*ListTunnelsRequest)(nil),       // 6: tunneledge.registry.v1.ListTunnelsRequest
	(*ListTunnelsResponse)(nil),      // 7: tunneledge.registry.v1.ListTunnelsResponse
	(*HeartbeatRequest)(nil),         // 8: tunneledge.registry.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 9: tunneledge.registry.v1.HeartbeatResponse
}
var file_proto_registry_v1_registry_proto_depIdxs = []int32{
	5, // 0: tunneledge.registry.v1.ListTunnelsResponse.tunnels:type_name -> tunneledge.registry.v1.GetTunnelResponse
	0, // 1: tunneledge.registry.v1.RegistryService.RegisterTunnel:input_type -> tunneledge.registry.v1.RegisterTunnelRequest
	2, // 2: tunneledge.registry.v1.RegistryService.DeregisterTunnel:input_type -> tunneledge.registry.v1.DeregisterTunnelRequest
	4, // 3: tunneledge.registry.v1.RegistryService.GetTunnel:input_type -> tunneledge.registry.v1.GetTunnelRequest
	6, // 4: tunneledge.registry.v1.RegistryService.ListTunnels:input_type -> tunneledge.registry.v1.ListTunnelsRequest
	8, // 5: tunneledge.registry.v1.RegistryService.Heartbeat:input_type -> tunneledge.registry.v1.HeartbeatRequest
	1, // 6: tunneledge.registry.v1.RegistryService.RegisterTunnel:output_type -> tunneledge.registry.v1.RegisterTunnelResponse
	3, // 7: tunneledge.registry.v1.RegistryService.DeregisterTunnel:output_type -> tunneledge.registry.v1.DeregisterTunnelResponse
	5, // 8: tunneledge.registry.v1.RegistryService.GetTunnel:output_type -> tunneledge.registry.v1.GetTunnelResponse
	7, // 9: tunneledge.registry.v1.RegistryService.ListTunnels:output_type -> tunneledge.registry.v1.ListTunnelsResponse
	9, // 10: tunneledge.registry.v1.RegistryService.Heartbeat:output_type -> tunneledge.registry.v1.HeartbeatResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_registry_v1_registry_proto_init() }
func file_proto_registry_v1_registry_proto_init() {
	if File_proto_registry_v1_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_registry_v1_registry_proto_rawDesc), len(file_proto_registry_v1_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_registry_v1_registry_proto_goTypes,
		DependencyIndexes: file_proto_registry_v1_registry_proto_depIdxs,
		MessageInfos:      file_proto_registry_v1_registry_proto_msgTypes,
	}.Build()
	File_proto_registry_v1_registry_proto = out.File
	file_proto_registry_v1_registry_proto_goTypes = nil
	file_proto_registry_v1_registry_proto_depIdxs = nil
}
